version: '2'

services:
    web:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./code:/code
            - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - code-network
        depends_on:
            - php
    php:
        build: .
        volumes:
            - ./code:/code
            - ./config/php-logs.conf:/usr/local/etc/php-fpm.d/zz-log.conf
        networks:
            - code-network
        depends_on:
            - datastore
    datastore:
        image: mongo:latest
        networks:
            - code-network
        ports:
            - "9001:9001"

networks:
    code-network:
        driver: bridge